services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - files-service
    networks:
      - app-network

  files-service:
    build:
      context: ./files-service
      dockerfile: Dockerfile
    container_name: files-service
    ports:
      - "8082:8082"
    volumes:
      - files-data:/app/files-data
    networks:
      - app-network

  database:
    image: postgres:15
    container_name: postgres-database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lcdci
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - app-network

volumes:
  files-data:
  db-data:

networks:
  app-network:
    driver: bridge
