services:

  #######################################################################
  # BACKEND (Spring Boot)
  #######################################################################
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    environment:
      FILE_SERVICE_URL: "http://files-service:8080"
    depends_on:
      files-service:
        condition: service_started
    networks:
      - app-network

  #######################################################################
  # FILES-SERVICE (Go + Gin + Postgres + MinIO)
  #######################################################################
  files-service:
    build:
      context: ./files-service
      dockerfile: Dockerfile
    container_name: files-service
    ports:
      - "8082:8080"  # IMPORTANT: map external 8082 -> internal 8080
    environment:
      DB_URL: "postgres://admin:admin@files-db:5432/filesdb?sslmode=disable"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "admin123"
    depends_on:
      files-db:
        condition: service_healthy
      minio:
        condition: service_started
    networks:
      - app-network

  #######################################################################
  # POSTGRES (files database)
  #######################################################################
  files-db:
    image: postgres:16
    container_name: files-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: filesdb
    ports:
      - "5433:5432"
      - "5433:5432"
    volumes:
      - ./files-service/migrations:/docker-entrypoint-initdb.d
      - files-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d filesdb"]
      interval: 3s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  #######################################################################
  # MINIO (S3-compatible object storage for files)
  #######################################################################
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO dashboard
    volumes:
      - minio-data:/data
    networks:
      - app-network

#######################################################################
# VOLUMES & NETWORK
#######################################################################
volumes:
  files-db-data:
  minio-data:

networks:
  app-network:
    driver: bridge
