version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lcdci-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: default
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend/les_constructions_dominic_cyr
      dockerfile: Dockerfile
    container_name: lcdci-frontend
    ports:
      - "3000:80"
    restart: unless-stopped

  files-service:
    build:
      context: ./files-service
      dockerfile: Dockerfile
    container_name: lcdci-files-service
    ports:
      - "8081:8081"
    restart: unless-stopped
